services:
  - type: web
    name: anttec-back
    env: docker
    plan: free
    branch: master
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link

    startCommand: ""

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://anttec-back.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-wilson.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: wilson_anttec
      - key: DB_USERNAME
        value: wilson
      - key: DB_PASSWORD
        value: "wilsonCMV
