services:
  - type: web
    name: anttec-laravel
    env: php
    rootDir: .
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan storage:link
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-wilson.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: wilson_anttec
      - key: DB_USERNAME
        value: wilson
      - key: DB_PASSWORD
        value: "wilsonCMV20:"
